<a href="https://colab.research.google.com/github/ml-nest/Modelling-stock-price-using-FR/blob/master/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Mounting GDrive
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive/MyDrive/github/Modelling-stock-price-using-FR/

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive/MyDrive/github/Modelling-stock-price-using-FR

# Scrapping financial data from screener.in

In [ ]:
from urllib.request import urlopen
import web_scrapping as ws
import pandas as pd
import numpy as np

In [ ]:
link = "https://www.screener.in/company/IOC/consolidated/"

page = urlopen(link)

html_bytes = page.read()
html = html_bytes.decode("utf-8")

## Quaterly Results

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
headings_value, temp, rest = ws.getting_headers(html, "Quarterly Results", "Profit & Loss")

qr_index = ['Sales', 'Expenses', 'Operating Profit', 'OPM %', 'Other Income', 'Interest', 
            'Depreciation', 'Profit before tax', 'Tax %', 'Net Profit', 'EPS in Rs']

quarter_results = pd.DataFrame(columns = headings_value)

for i in qr_index:
    values, temp = ws.func(temp, i, "td", headings_value)
    quarter_results.loc[i] = ws.string_to_float(values)

In [ ]:
quarter_results

                    Mar 2018  Jun 2018  ...  Sep 2020   Dec 2020
Sales              116956.00  128707.0  ...   81704.0  101969.00
Expenses           105539.00  115645.0  ...   71513.0   92176.00
Operating Profit    11418.00   13062.0  ...   10192.0    9794.00
OPM %                  10.00      10.0  ...      12.0      10.00
Other Income          488.00     847.0  ...    1290.0    1235.00
Interest             1344.00    1153.0  ...     320.0     734.00
Depreciation         2134.00    1961.0  ...    2656.0    2723.00
Profit before tax    8428.00   10795.0  ...    8506.0    7572.00
Tax %                  33.00      34.0  ...      28.0      46.00
Net Profit           5527.00    7092.0  ...    6026.0    4359.00
EPS in Rs               5.69       7.3  ...       6.4       4.63

[11 rows x 12 columns]

## Profit Loss

In [ ]:
headings_value, temp, rest = ws.getting_headers(rest, "Profit & Loss", "Balance Sheet")

pl_index = ['Sales', 'Expenses', 'Operating Profit', 'OPM %', 'Other Income', 'Interest', 
            'Depreciation', 'Profit before tax', 'Tax %', 'Net Profit', 'EPS in Rs', 'Dividend Payout %']

pl_results = pd.DataFrame(columns = headings_value)

for i in pl_index:
    values, temp = ws.func(temp, i, "td", headings_value)
    pl_results.loc[i] = ws.string_to_float(values)

In [ ]:
pl_results

,Mar 2009,Mar 2010,Mar 2011,Mar 2012,Mar 2013,Mar 2014,Mar 2015,Mar 2016,Mar 2017,Mar 2018,Mar 2019,Mar 2020,TTM
Sales,288670.00,250046.00,309797.00,408923.00,461780.00,488345.0,449507.00,346045.00,355379.00,421492.00,528158.00,484362.00,362210.00
Expenses,281875.00,236613.00,295154.00,389402.00,447887.00,471251.0,438948.00,322584.00,321274.00,379834.00,492896.00,467906.00,339077.00
Operating Profit,6795.00,13433.00,14643.00,19521.00,13892.00,17094.0,10559.00,23461.00,34105.00,41658.00,35262.00,16456.00,23133.00
OPM %,2.00,5.00,5.00,5.00,3.00,4.0,2.00,7.00,10.00,10.00,7.00,3.00,6.00
Other Income,4325.00,6948.00,3421.00,-4268.00,3468.00,5192.0,5876.00,3796.00,4399.00,4331.00,4097.00,-7148.00,-6105.00
Interest,4282.00,1777.00,3017.00,5948.00,7164.00,5948.0,4201.00,3487.00,3743.00,3875.00,4925.00,6630.00,4418.00
Depreciation,3189.00,3555.00,4933.00,5309.00,5692.00,6360.0,5219.00,5698.00,6806.00,7664.00,8506.00,9855.00,10645.00
Profit before tax,3649.00,15049.00,10114.00,3995.00,4504.00,9978.0,7014.00,18072.00,27956.00,34450.00,25927.00,-7177.00,1965.00
Tax %,34.00,27.00,20.00,-7.00,19.00,30.0,31.00,31.00,27.00,34.00,33.00,74.00,NaN
Net Profit,2599.00,10713.00,7831.00,4226.00,4449.00,7086.0,4912.00,12022.00,19849.00,22189.00,17377.00,-893.00,4829.00
EPS in Rs,2.73,11.03,8.06,4.35,4.58,7.3,5.06,12.38,20.44,22.85,18.46,-0.95,5.13
Dividend Payout %,36.00,30.00,30.00,30.00,36.00,30.0,33.00,28.00,45.00,90.00,49.00,-437.00,NaN

## Balance Sheet

In [ ]:
headings_value, temp, rest = ws.getting_headers(rest, "Balance Sheet", "Cash Flows")

bs_index = ['Share Capital', 'Reserves', 'Borrowings', 'Other Liabilities', 'Total Liabilities', 'Fixed Assets', 
            'CWIP', 'Investments', 'Other Assets', 'Total Assets']

bs_results = pd.DataFrame(columns = headings_value)

for i in bs_index:
    values, temp = ws.func(temp, i, "td", headings_value)
    bs_results.loc[i] = ws.string_to_float(values)

In [ ]:
bs_results

,Mar 2009,Mar 2010,Mar 2011,Mar 2012,Mar 2013,Mar 2014,Mar 2015,Mar 2016,Mar 2017,Mar 2018,Mar 2019,Mar 2020,Sep 2020
Share Capital,1214.0,2428.0,2428.0,2428.0,2428.0,2428.0,2428.0,2370.0,4739.0,9479.0,9181.0,9181.0,9181.0
Reserves,44290.0,50034.0,55147.0,57945.0,60608.0,65485.0,66404.0,87610.0,97357.0,104395.0,103288.0,86217.0,94656.0
Borrowings,47347.0,49472.0,57763.0,80015.0,89671.0,94916.0,64893.0,58552.0,63271.0,65650.0,96765.0,129790.0,97415.0
Other Liabilities,43627.0,52823.0,69263.0,79438.0,89171.0,103124.0,100158.0,83184.0,108352.0,116336.0,126128.0,104773.0,128960.0
Total Liabilities,136457.0,154758.0,184601.0,219827.0,241878.0,265953.0,233883.0,231715.0,273719.0,295860.0,335363.0,329962.0,330212.0
Fixed Assets,38453.0,45458.0,62681.0,64586.0,66707.0,69724.0,72844.0,95761.0,112031.0,119937.0,127223.0,141594.0,151749.0
CWIP,19169.0,22810.0,10866.0,15450.0,27240.0,38061.0,40378.0,26219.0,16778.0,19130.0,28281.0,32845.0,31868.0
Investments,31324.0,21430.0,18647.0,17588.0,17351.0,15895.0,16069.0,31185.0,43687.0,44806.0,44112.0,35571.0,35889.0
Other Assets,47511.0,65061.0,92407.0,122203.0,130580.0,142273.0,104592.0,78551.0,101222.0,111987.0,135746.0,119952.0,110706.0
Total Assets,136457.0,154758.0,184601.0,219827.0,241878.0,265953.0,233883.0,231715.0,273719.0,295860.0,335363.0,329962.0,330212.0

## Cash Flows

In [ ]:
headings_value, temp, rest = ws.getting_headers(rest, "Cash Flows", "Ratios")

cf_index = ['Cash from Operating Activity', 'Cash from Investing Activity', 'Cash from Financing Activity', 'Net Cash Flow']

cf_results = pd.DataFrame(columns = headings_value)

for i in cf_index:
    values, temp = ws.func(temp, i, "td", headings_value)
    cf_results.loc[i] = ws.string_to_float(values)

In [ ]:
cf_results

,Mar 2009,Mar 2010,Mar 2011,Mar 2012,Mar 2013,Mar 2014,Mar 2015,Mar 2016,Mar 2017,Mar 2018,Mar 2019,Mar 2020
Cash from Operating Activity,-21341.0,-1609.0,6819.0,-763.0,9340.0,24195.0,46092.0,25624.0,28216.0,29115.0,12747.0,8653.0
Cash from Investing Activity,18337.0,3595.0,-8090.0,-13056.0,-9294.0,-18594.0,-10215.0,-13610.0,-17684.0,-17119.0,-22569.0,-29097.0
Cash from Financing Activity,2949.0,-1392.0,1211.0,13103.0,352.0,-3116.0,-38283.0,-11890.0,-10937.0,-12007.0,10436.0,20945.0
Net Cash Flow,-55.0,593.0,-61.0,-716.0,398.0,2485.0,-2406.0,124.0,-405.0,-11.0,614.0,502.0

## Ratios

In [ ]:
headings_value, temp, rest = ws.getting_headers(rest, "Ratios", "Shareholding Pattern")

ratio_index = ['ROCE %', 'Debtor Days', 'Inventory Turnover']

ratio_results = pd.DataFrame(columns = headings_value)

for i in ratio_index:
    values, temp = ws.func(temp, i, "td", headings_value)
    ratio_results.loc[i] = ws.string_to_float(values)

In [ ]:
ratio_results

,Mar 2009,Mar 2010,Mar 2011,Mar 2012,Mar 2013,Mar 2014,Mar 2015,Mar 2016,Mar 2017,Mar 2018,Mar 2019,Mar 2020
ROCE %,10.00,18.00,12.00,14.00,8.00,9.00,6.00,14.00,20.00,22.00,16.00,5.00
Debtor Days,6.00,8.00,9.00,10.00,10.00,9.00,6.00,8.00,9.00,9.00,11.00,10.00
Inventory Turnover,7.82,6.26,5.71,6.16,6.43,6.31,6.62,6.27,5.16,5.01,6.06,5.82

## Shareholding Pattern

In [ ]:
headings_value, temp, rest = ws.getting_headers(rest, "Shareholding Pattern", "Documents")

sp_index = ['Promoters', 'FIIs', 'DIIs', 'Government', 'Public']

sp_results = pd.DataFrame(columns = headings_value)

for i in sp_index:
    values, temp = ws.func(temp, i, "td", headings_value)
    sp_results.loc[i] = ws.string_to_float(values)

In [ ]:
sp_results

,Mar 2018,Jun 2018,Sep 2018,Dec 2018,Mar 2019,Jun 2019,Sep 2019,Dec 2019,Mar 2020,Jun 2020,Sep 2020,Dec 2020
Promoters,56.98,56.75,56.75,54.06,52.18,52.18,51.50,51.50,51.50,51.50,51.50,51.50
FIIs,6.16,5.85,5.98,5.60,7.04,7.66,7.23,7.64,7.19,6.33,6.07,5.83
DIIs,10.33,11.18,11.05,13.47,13.72,13.13,14.25,13.79,13.40,13.85,13.37,13.54
Government,0.11,0.11,0.11,0.11,0.11,0.11,0.11,0.11,0.11,0.11,0.11,0.11
Public,26.43,26.10,26.11,26.76,26.95,26.91,26.91,26.95,27.80,28.20,28.95,29.02